title: Code and Conquer
email: your-email@example.com
description: >- # this means to ignore newlines until 
  A simple Jekyll site running in Docker.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site


# jekyll-seo-tag configuration
author: "Ms Aziz & Mr Mulla"
url: "codeandconquer.org"
title: "CODEANDCONQUER.org"
description: "Learn OCR A Level Computer Science with Ms Aziz & Mr Mulla"
twitter:
  username: ""
  card: ""
logo: "/assets/images/c&c_logo.png"

encoding: utf-8
markdown: kramdown
# Build settings
theme: minima
plugins:
  - jekyll-feed
