title: Code and Conquer
email: your-email@example.com
description: >- # this means to ignore newlines until 
  A simple Jekyll site running in Docker.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
theme: minima
plugins:
  - jekyll-feed
